import NewYork from "@/components/resume-samples/NewYork";
import Toronto from "@/components/resume-samples/Toronto";

export const TEMPLATES = [
  {
    id: 1,
    name: "Toronto",
    text: "A web-inspired resume template perfect for chatting up your achievements.",
    img: "/Toronto.jpg",
    design: "Simple",
    type: ["pdf", "docx"],
    component: Toronto,
    color: "",
  },
  {
    id: 2,
    name: "Stockholm",
    text: "Perfect balance of fresh and functional resume template design.",
    img: "/Stockholm.jpg",
    design: "Simple",
    type: ["pdf", "docx"],
    component: Toronto,
    color: "",
  },
  {
    id: 3,
    name: "London",
    text: "Classically structured resume template, for a rebust career history.",
    img: "/London.jpg",
    design: "Simple",
    type: ["pdf", "docx"],
    component: Toronto,
    color: "",
  },
  {
    id: 4,
    name: "Dublin",
    text: "A touch of personality with a well-organized resume structure.",
    img: "/Dublin.jpg",
    design: "Modern",
    type: ["pdf"],
    component: Toronto,
    color: "",
  },
  {
    id: 5,
    name: "New York",
    text: "Professional and elegant resume template with a timeline structure.",
    img: "/New_york.jpg",
    design: "Professional",
    type: ["pdf", "docx"],
    component: NewYork,
  },
  {
    id: 6,
    name: "Vienna",
    text: "Striking modern header, professional two column templates structure",
    img: "/Vienna.jpg",
    design: "Modern",
    type: ["pdf", "docx"],
    component: Toronto,
    color: "",
  },
  {
    id: 7,
    name: "Sydney",
    text: "Modern and eye-catching resume template. Beautiful contrasting structure.",
    img: "/Sydney.jpg",
    design: "Professional",
    type: ["docx"],
    component: Toronto,
    color: "",
  },
  {
    id: 8,
    name: "Moscow",
    text: "Open white-space template, excellent readability.",
    img: "",
    design: "Professional",
    type: ["pdf", "docx"],
    component: Toronto,
    color: "",
  },
  {
    id: 9,
    name: "Amsterdam",
    text: "Modern minimalist resume template structure with gracecful clarity.",
    img: "",
    design: "Simple",
    type: ["pdf"],
    component: Toronto,
    color: "",
  },
  {
    id: 10,
    name: "Madrid",
    text: "Powerful modern resume template with bold section highlights.",
    img: "",
    design: "Simple",
    type: ["pdf", "docx"],
    component: Toronto,
    color: "",
  },
];
